#!/bin/sh

. /lib/ar71xx.sh
. /lib/functions.sh
. /lib/functions/system.sh

set_5g_macaddr()
{
	config_load wireless
	config_foreach set_macaddr wifi-iface
}

set_macaddr()
{
	local device path

	config_load wireless

	config_get device "$1" device
	config_get path $device path

	if [ -n "`echo $path | grep "pci0000"`" ] ; then
		uci -q set wireless.$1.macaddr="$(macaddr_add $(cat /sys/class/net/eth1/address) +0)"
		uci -q commit wireless
	fi
}

#if [ -n "`df -h | grep overlayfs`" ]; then

while true; do
	if [ -f /etc/urandom.seed ]; then
	
		uci -q batch <<-EOF >/dev/null
			set wireless.radio0.disabled='0'
			set wireless.radio1.disabled='0'
			commit wireless
		EOF
	
		set_5g_macaddr
		break
	fi
	sleep 10
done

wifi

exit 0

